USE [ANIMEDATA_DEV]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

BEGIN TRAN

SELECT * 
INTO dbo.T_ANIME_TBL_14
FROM dbo.T_ANIME_TBL

DROP TABLE [dbo].[T_ANIME_TBL]

CREATE TABLE [dbo].[T_ANIME_TBL](
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_CHN_NAME] [varchar](255) NOT NULL,
	[ANIME_JPN_NAME] [varchar](255) NOT NULL,
	[ANIME_ALP_NAME] varchar(1000) NULL,
	[ANIME_NN] [varchar](10) NOT NULL,
	[STATUS] [smallint] NOT NULL,
	[ORIGINAL] [smallint] NOT NULL,
	[MUSIC_STATUS] [smallint] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_USER_ID] varchar(100) NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_TBL] PRIMARY KEY CLUSTERED 
(
	[ANIME_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO T_ANIME_TBL
(
[ANIME_NO],
[ANIME_CHN_NAME],
[ANIME_JPN_NAME],
[ANIME_ALP_NAME],
[ANIME_NN],
[STATUS],
[ORIGINAL],
[MUSIC_STATUS],
[ENABLE_FLG],
[LAST_UPDATE_USER_ID],
[LAST_UPDATE_DATETIME]
)
SELECT 
[ANIME_NO],
[ANIME_CHN_NAME],
[ANIME_JPN_NAME],
'',
[ANIME_NN],
[STATUS],
[ORIGINAL],
[MUSIC_STATUS],
[ENABLE_FLG],
'#14',
[LAST_UPDATE_DATETIME]
FROM dbo.T_ANIME_TBL_14

SELECT * FROM dbo.T_ANIME_TBL_14
SELECT * FROM dbo.T_ANIME_TBL

DROP TABLE dbo.T_ANIME_TBL_14

--COMMIT

--ROLLBACK