USE [ANIMEDATA_DEV]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

BEGIN TRAN

SELECT * 
INTO dbo.T_CHARACTER_TBL_14
FROM dbo.T_CHARACTER_TBL

DROP TABLE [dbo].T_CHARACTER_TBL

--SELECT * FROM ANIMEDATA_DEV.dbo.T_CHARACTER_TBL_14 

SELECT 
      [ANIME_NO]
	  ,CAST(NULL AS int) AS CHARACTER_NO
      ,[CHARACTER_NAME] AS CHARACTER_CHN_NAME
	  ,'' AS CHARACTER_JPN_NAME
      ,[CV_ID]
      ,[LEADING_FLG]
      ,[ENABLE_FLG]
	  ,'#14' AS [LAST_UPDATE_USER_ID]
      ,[LAST_UPDATE_DATETIME]
	  ,CHARACTER_NO as old_no
	  INTO #tmp
 FROM ANIMEDATA_DEV.dbo.T_CHARACTER_TBL_14 

--select * from #tmp
  

DECLARE @cur_anime_no char(4)

DECLARE anime_cur CURSOR FOR  SELECT DISTINCT ANIME_NO FROM #tmp
OPEN anime_cur
FETCH NEXT FROM anime_cur INTO @cur_anime_no
WHILE @@FETCH_STATUS = 0 
BEGIN
	BEGIN 
		DECLARE @old_no varchar(10)
		
		DECLARE @lead_no int = 0
		DECLARE @unlead_no int = 0
			
		DECLARE conv_cur CURSOR LOCAL FOR
					SELECT
					DISTINCT old_no
					FROM #tmp
					WHERE ANIME_NO = @cur_anime_no

		OPEN conv_cur
		FETCH NEXT FROM conv_cur INTO @old_no
		WHILE @@FETCH_STATUS = 0 
		BEGIN
			DECLARE @flg bit =0
			
			SELECT @flg = LEADING_FLG FROM #tmp WHERE old_no = @old_no
			IF(@flg = 1)
			BEGIN
				SET @lead_no = @lead_no + 1
				UPDATE #tmp SET CHARACTER_NO = 10000 + @lead_no WHERE old_no = @old_no
				
			END
			ELSE BEGIN
				SET @unlead_no = @unlead_no + 1
				UPDATE #tmp SET CHARACTER_NO = 20000 + @unlead_no WHERE old_no = @old_no
			END
			
			FETCH NEXT FROM conv_cur INTO @old_no
		END

		CLOSE conv_cur
		DEALLOCATE conv_cur
	END
	
	FETCH NEXT FROM anime_cur INTO @cur_anime_no
END
CLOSE anime_cur
DEALLOCATE anime_cur


--select * from #tmp
  
CREATE TABLE [dbo].[T_CHARACTER_TBL](
	CHARACTER_ID int identity(1,1) Not Null,
	ANIME_NO [char](4) NOT NULL,
	CHARACTER_NO int NOT NULL,
	CHARACTER_CHN_NAME [varchar](1000) NOT NULL,
	CHARACTER_JPN_NAME [varchar](1000) NOT NULL,
	CV_ID [int] NOT NULL,
	LEADING_FLG [bit] NOT NULL DEFAULT ((0)),
	ENABLE_FLG [bit] NOT NULL DEFAULT ((1)),
	LAST_UPDATE_USER_ID varchar(100) NOT NULL,
	LAST_UPDATE_DATETIME [datetime] NOT NULL DEFAULT (getdate())
 CONSTRAINT [PK_T_CHARACTER_TBL] PRIMARY KEY CLUSTERED 
(
	CHARACTER_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)

INSERT INTO [dbo].[T_CHARACTER_TBL] (
ANIME_NO
,CHARACTER_NO
,CHARACTER_CHN_NAME
,CHARACTER_JPN_NAME
,CV_ID
,LEADING_FLG
,ENABLE_FLG 
,LAST_UPDATE_USER_ID
,LAST_UPDATE_DATETIME
)
SELECT 
ANIME_NO
,CHARACTER_NO
,CHARACTER_CHN_NAME
,CHARACTER_JPN_NAME
,CV_ID
,LEADING_FLG
,ENABLE_FLG 
,LAST_UPDATE_USER_ID
,LAST_UPDATE_DATETIME
FROM #tmp 
ORDER BY ANIME_NO ASC ,CHARACTER_NO ASC


--commit

--rollback
