USE [ANIMEDATA_DEV]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

BEGIN TRAN

SELECT * 
INTO dbo.T_COMPANY_TBL_14
FROM dbo.T_COMPANY_TBL

DROP TABLE [dbo].T_COMPANY_TBL

CREATE TABLE [dbo].[T_COMPANY_TBL](
	[COMPANY_ID] [int] NOT NULL,
	[COMPANY_CHN_NAME] [varchar](1000) NOT NULL,
	[COMPANY_JPN_NAME] [varchar](1000) NOT NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_USER_ID] varchar(100) NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_COMPANY_TBL] PRIMARY KEY CLUSTERED 
(
	[COMPANY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO dbo.T_COMPANY_TBL
([COMPANY_ID]
,[COMPANY_CHN_NAME]
,[COMPANY_JPN_NAME]
,[ENABLE_FLG]
,[LAST_UPDATE_USER_ID]
,[LAST_UPDATE_DATETIME]
)
SELECT 
[COMPANY_ID]
,[COMPANY_NAME]
,''
,[ENABLE_FLG]
,'#14'
,[LAST_UPDATE_DATETIME]
FROM dbo.T_COMPANY_TBL_14

SELECT * FROM dbo.T_COMPANY_TBL_14
SELECT * FROM dbo.T_COMPANY_TBL

DROP TABLE dbo.T_COMPANY_TBL_14

--COMMIT

--ROLLBACK