USE [ANIMEDATA_DEV]
GO

/****** Object:  Table [dbo].[T_CV_TBL]    Script Date: 2016/12/09 15:07:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO


BEGIN TRAN

SELECT * 
INTO dbo.[T_CV_TBL_14]
FROM dbo.[T_CV_TBL]

DROP TABLE [dbo].[T_CV_TBL]

CREATE TABLE [dbo].[T_CV_TBL](
	[CV_ID] [int] NOT NULL,
	[CV_CHN_NAME] [varchar](1000) NULL,
	[CV_JPN_NAME] [varchar](1000) NOT NULL,
	CV_KANA_NAME [varchar](1000) NULL,
	CV_ALP_NAME [varchar](1000) NULL,
	[CV_GENDER] [char](1) NULL,
	[CV_BIRTH] [date] NULL,
	[CV_OFFICE_ID] [int] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_USER_ID] varchar(100) NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_CV_TBL] PRIMARY KEY CLUSTERED 
(
	[CV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO [dbo].[T_CV_TBL]
(
[CV_ID]
,CV_CHN_NAME  
,CV_JPN_NAME
,CV_KANA_NAME 
,CV_ALP_NAME 
,[CV_GENDER]
,[CV_BIRTH]
,[CV_OFFICE_ID]
,[ENABLE_FLG]
,[LAST_UPDATE_USER_ID]
,[LAST_UPDATE_DATETIME]
)
SELECT 
[CV_ID]
,[CV_NAME]
,[CV_NAME]
,''
,''
,[CV_GENDER]
,[CV_BIRTH]
,[CV_OFFICE_ID]
,[ENABLE_FLG]
'#14'
,[LAST_UPDATE_DATETIME]
FROM dbo.T_CV_TBL_14


SELECT * FROM dbo.T_CV_TBL_14
SELECT * FROM dbo.T_CV_TBL

DROP TABLE dbo.T_CV_TBL_14

--COMMIT

--ROLLBACK