USE [ANIMEDATA_DEV]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

BEGIN TRAN

SELECT * 
INTO dbo.T_PLAYINFO_TBL_14
FROM dbo.T_PLAYINFO_TBL

DROP TABLE [dbo].T_PLAYINFO_TBL

CREATE TABLE [dbo].[T_PLAYINFO_TBL](
	[PLAYINFO_ID] [int] NOT NULL,
	[ANIME_NO] [char](4) NOT NULL,
	[ANIME_PLAYINFO] [varchar](255) NOT NULL,
	[STATUS] [smallint] NOT NULL,
	[ORIGINAL] [smallint] NOT NULL,
	[START_TIME] [date] NULL,
	[WATCH_TIME] [date] NULL,
	[PARTS] [int] NULL,
	[COMPANY_ID] [int] NULL,
	[ENABLE_FLG] [bit] NOT NULL DEFAULT ((1)),
	[LAST_UPDATE_USER_ID] varchar(100) NOT NULL,
	[LAST_UPDATE_DATETIME] [datetime] NOT NULL DEFAULT (getdate()),
 CONSTRAINT [PK_T_PLAYINFO_TBL] PRIMARY KEY CLUSTERED 
(
	[PLAYINFO_ID] ASC,
	[ANIME_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


INSERT INTO T_PLAYINFO_TBL
(
[PLAYINFO_ID]
,[ANIME_NO]
,[ANIME_PLAYINFO]
,[STATUS]
,[ORIGINAL]
,[START_TIME]
,[WATCH_TIME]
,[PARTS]
,[COMPANY_ID]
,[ENABLE_FLG]
,[LAST_UPDATE_USER_ID]
,[LAST_UPDATE_DATETIME]
)
SELECT 
[PLAYINFO_ID]
,[ANIME_NO]
,[ANIME_PLAYINFO]
,[STATUS]
,9
,[START_TIME]
,[WATCH_TIME]
,[PARTS]
,[COMPANY_ID]
,[ENABLE_FLG]
,'#14'
,[LAST_UPDATE_DATETIME]
FROM dbo.T_PLAYINFO_TBL_14

SELECT * FROM dbo.T_PLAYINFO_TBL_14
SELECT * FROM dbo.T_PLAYINFO_TBL

DROP TABLE dbo.T_PLAYINFO_TBL_14

--COMMIT

--ROLLBACK